# Generated by Django 3.2.8 on 2021-10-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0002_rename_employeename_employees_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='DateOfJoining',
        ),
    ]
