# Generated by Django 3.2.8 on 2021-10-11 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0003_remove_employees_dateofjoining'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
