# Generated by Django 3.2.8 on 2021-10-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_app', '0004_employees_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='created_at',
            new_name='DateOfJoining',
        ),
    ]
